name: LunikerDynamicWorld
version: 1.0
author: 2sk
website: luniker.net

main: net.luniker.lunikerdynamicworld.LunikerDynamicWorld
database: false
softdepend: [WorldEdit]

commands:
  dynamics:
    description: Enter the Dynamics Factory.
    usage: /dynamics
    permission: lunikerdynamicworld.dynamics

permissions:
  lunikerdynamicworld.*:
    description: Gives access to all Luniker Dynamic World commands.
    children:
      lunikerdynamicworld.dynamics: true
  lunikerdynamicworld.dynamics:
    description: Allows you to make, edit and view Luniker Dynamic World Objects.
    default: true
